(function () {

    var shortLivedAccessToken = undefined;
    var weeklyStats = {
        weeklyRunsTotal: null,
        weeklyMilage: null,
        weeklyTotalMinutes: null,
        weeklyArr: [null, null, null, null, null, null, null]
    };

    function refreshAccessToken() {
        logger.logDebug("refresshing access tokens for strava");
        try {
            let xhr = new XMLHttpRequest();
            xhr.open("POST", config.stravaTokenRefreshEndpoint, true);

            //Send the proper header information along with the request
            xhr.setRequestHeader("Accept", "application/json");
            xhr.setRequestHeader("Content-Type", "application/json");

            //set body of request
            var body = {
                client_id: config.strava.client_id,
                client_secret: config.strava.client_secret,
                grant_type: config.strava.grant_type,
                refresh_token: config.strava.strava_refreshToken
            }

            //leaving this here for reference for now. 
            //this was for setup to authenticate a change in the permissions
            //this app has to a Strava athlete's viewable data
            //if you wish to change the permissions to say 'activity:read_all'
            //to read all activities, you'll have to resend the req via this body
            //var body = {
            //    client_id: config.strava.client_id,
            //    client_secret: config.strava.client_secret,
            //    code: "", //this code is generated by strava when you change your permissions
            //    grant_type: "authorization_code"
            //}

            xhr.onreadystatechange = function () {
                if (this.readyState === XMLHttpRequest.DONE) {
                    if (this.status === 200) {
                        //maybe we should return a promise?
                        //refresh our token
                        processRefreshTokenResponse(JSON.parse(this.response));
                        //use getStravaData() to send another HTTP req
                        getStravaData();
                    } else {
                        logger.logError("Error sending Strava Refresh Token HTTP request");
                    }                  
                }
            };
            xhr.send(JSON.stringify(body));
        } catch (err) {
            logger.logError(err);
        }
    }

    /*
     * For more information on the topic see https://developers.strava.com/docs/reference/#api-models-ActivityStats
     * There's a TON of categories
     */
    function getStravaData() {
        try {
            let beforeTime = new Date();
            let afterTime = new Date();

            //if Sunday
            if (afterTime.getDay() == 0) {
                afterTime.setDate(afterTime.getDate() - 6);
            } else {
                //if M - Sa
                afterTime.setDate(afterTime.getDate() - afterTime.getDay() + 1);
                afterTime.setHours(0, 0, 0);
            }

            let before = (beforeTime.getTime() / 1000).toFixed(0);
            let after = (afterTime.getTime() / 1000).toFixed(0);

            let request = new XMLHttpRequest();
            request.open(
                "GET",
                `${config.stravaAtheleteEndpoint}?before=${before}&after=${after}`,
                true);

            request.setRequestHeader("Authorization", `Bearer ${shortLivedAccessToken}`);
            request.onreadystatechange = function () {
                if (this.readyState == XMLHttpRequest.DONE) {
                    if (this.status == 200) {
                        processStravaDataResponse(JSON.parse(this.response));
                    } else {
                        logger.logError(`Error making HTTP request to ${config.stravaAtheleteEndpoint}`);
                    }
                }
            };
            request.send();
        } catch (error) {
            logger.logError(`Problem calling Strava Api : ${error}`);
            return;
        }
    }

    function processStravaDataResponse(data) {
        logger.log("Processing response from Strava Athlete Api");

        if (data === undefined || !Array.isArray(data)) {
            logger.logDebug("The data returned from the http request was undefined or the data returned was not an array");
            return;
        }

        //each element in the array is an activity that was recorded
        data.forEach(function parseActivityObj(activity, idx) {
            if (activity.type.toLowerCase() === "run") {

                //TODO: use activity.start_date property to compare to today.
                //use this to find the activities for Monday - Sunday
                //store the activities for each day of the week in the activty array

                weeklyStats.weeklyRunsTotal += 1;

                if (activity.distance != undefined) {
                    //convert meters to miles
                    weeklyStats.weeklyMilage += (activity.distance * 0.000621371);
                    weeklyStats.weeklyArr[idx] += parseFloat((activity.distance * 0.000621371).toFixed(0));
                }

                if (activity.elapsed_time != undefined) {
                    //convert sec to minutes
                    weeklyStats.weeklyTotalMinutes += (activity.elapsed_time / 60);
                }
            }            
        });

        console.log("weeklyStats");
        console.log(weeklyStats);
        renderWeeklyStatsHtml();
        renderBarChartsHtml();
    }

    function processRefreshTokenResponse(data) {
        logger.log("Processing response from Strava Refresh Token");

        console.log(data);

        if (data === undefined || data.access_token === undefined) {
            logger.logDebug("The data returned from the http request was undefined or there was no access_token");
            return;
        }

        shortLivedAccessToken = data.access_token;
        config.strava.strava_refreshToken = data.refresh_token;
    }

    function renderWeeklyStatsHtml() {
        logger.logDebug("Rendering the Strava Component HTML DOM");

        let weeklyHeader = document.createElement("h1")
        weeklyHeader.id = "weeklyHeader";
        weeklyHeader.innerText = "This Week's Performance"
        document.getElementById("topRightContainer").appendChild(weeklyHeader);

        let stravaTopContainer = document.createElement("div");
        stravaTopContainer.id = "stravaTopContainer";
        let stravaBotContainer = document.createElement("div");
        stravaBotContainer.id = "stravaBotContainer";
        document.getElementById("topRightContainer").appendChild(stravaTopContainer);
        document.getElementById("topRightContainer").appendChild(stravaBotContainer);

        let weeklyActivitiesContainer = document.createElement("div");
        weeklyActivitiesContainer.id = "weeklyDiv";
        let weeklyMilageContainer = document.createElement("div");
        weeklyMilageContainer.id = "weeklyDiv";
        let weeklyTotalMinutesContainer = document.createElement("div");
        weeklyTotalMinutesContainer.id = "weeklyDiv";

        let weeklyActivitesHeader = document.createElement("h2");
        let weeklyMilageHeader = document.createElement("h2");
        let weeklyTotalMinutesHeader = document.createElement("h2");
        weeklyActivitesHeader.id = "weeklyStatHeader";
        weeklyMilageHeader.id = "weeklyStatHeader";
        weeklyTotalMinutesHeader.id = "weeklyStatHeader";
        weeklyActivitesHeader.innerText = "Total Runs";
        weeklyMilageHeader.innerText = "Total Milage";
        weeklyTotalMinutesHeader.innerText = "Total Minutes";

        let weeklyActivitesImg = document.createElement("img");
        let weeklyMilageImg = document.createElement("img");
        let weeklyTotalMinutesImg = document.createElement("img");
        weeklyActivitesImg.src = config.image.runner;
        weeklyMilageImg.src = config.image.road; 
        weeklyTotalMinutesImg.src = config.image.stopwatch;
        weeklyActivitesImg.id = "weeklyActivitesImg";
        weeklyMilageImg.id = "weeklyMilageImg";
        weeklyTotalMinutesImg.id = "weeklyTotalMinutesImg";

        stravaTopContainer.appendChild(weeklyActivitiesContainer);
        stravaTopContainer.appendChild(weeklyMilageContainer);
        stravaTopContainer.appendChild(weeklyTotalMinutesContainer);

        weeklyActivitiesContainer.appendChild(weeklyActivitesHeader);
        weeklyMilageContainer.appendChild(weeklyMilageHeader);
        weeklyTotalMinutesContainer.appendChild(weeklyTotalMinutesHeader);

        weeklyActivitiesContainer.appendChild(weeklyActivitesImg);
        weeklyMilageContainer.appendChild(weeklyMilageImg);
        weeklyTotalMinutesContainer.appendChild(weeklyTotalMinutesImg);

        weeklyMilageContainer.appendChild(document.createElement("br"));
        weeklyActivitiesContainer.appendChild(document.createElement("br"));
        weeklyTotalMinutesContainer.appendChild(document.createElement("br"));

        let runs = document.createElement("h3");
        let mileage = document.createElement("h3");
        let totalMinutes = document.createElement("h3");
        runs.id = "statistic";
        mileage.id = "statistic";
        totalMinutes.id = "statistic";
        runs.innerText = weeklyStats.weeklyRunsTotal;
        mileage.innerText = weeklyStats.weeklyMilage.toFixed(2);
        totalMinutes.innerText = weeklyStats.weeklyTotalMinutes.toFixed(0);

        weeklyActivitiesContainer.appendChild(runs)
        weeklyMilageContainer.appendChild(mileage);
        weeklyTotalMinutesContainer.appendChild(totalMinutes);
    }

    function renderBarChartsHtml() {

        var Chart = require('chart.js');

        let weeklyRunGraphContainer = document.createElement("div");
        let monthlyRunGraphContainer = document.createElement("div");
        let yearlyRunGraphContainer = document.createElement("div");

        let weeklyRunCanvas = document.createElement("canvas");
        let monthlyRunCanvas = document.createElement("canvas");
        let yearlyRunCanvas = document.createElement("canvas");

        weeklyRunCanvas.id = "weeklyRunCanvas";
        monthlyRunCanvas.id = "monthlyRunCanvas";
        yearlyRunCanvas.id = "yearlyRunCanvas";

        weeklyRunGraphContainer.appendChild(weeklyRunCanvas);
        monthlyRunGraphContainer.appendChild(monthlyRunCanvas);
        yearlyRunGraphContainer.appendChild(yearlyRunCanvas);

        document.getElementById("stravaBotContainer").appendChild(weeklyRunGraphContainer);
        //document.getElementById("stravaBotContainer").appendChild(monthlyRunGraphContainer);
        //document.getElementById("stravaBotContainer").appendChild(yearlyRunGraphContainer);

        let weeklyChart = new Chart(weeklyRunCanvas, {
            type: 'bar',
            data: {
                labels: ['M', 'Tu', 'W', 'Th', 'F', 'Sa', 'Su'],
                datasets: [{
                    data: weeklyStats.weeklyArr,
                    backgroundColor: 'rgba(0, 0, 0, 1)',
                    borderColor: 'rgba(0, 0, 0, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                responsive: false,
                maintainAspectRatio: true,
                title: {
                    display: true,
                    text: "Weekly Miles",
                    fontColor: 'rgba(0, 0, 0, 1)',
                    padding: 15
                },
                legend: {
                    display: false,
                },
                scales: {
                    xAxes: [{
                        gridLines: {
                            display: false
                        },
                        ticks: {
                            fontColor: 'rgba(0, 0, 0, 1)'
                        }
                    }],
                    yAxes: [{
                        display: false
                    }]
                },
            },
        });
    }

    refreshAccessToken();

    //TODO:     renderStravaHtml(); once you make other functions into promises... theres no reason
    //we cant render the HTML after thats done... think about this

})();